var req = require("request");

var seq = ">candidate\nMMNQNCFNSCSPLTVDALEPKKSSCAAKCIQVNGPLIVGAGPSGLATAAVLKQYSVPYVIIERADCIASLWQHKTYDRLRLNVPRQYCELPGLPFPPDFPEYPTKNQFISYLVSYAKHFEIKPQLNESVNLAGYDETCGLWKVKTVSEINGSTSEYMCKWLIVATGENAEMIVPEFEGLQDFGGQVIHACEYKTGEYYTGENVLAVGCGNSGIDISLDLSQHNANPFMVVRSSVQGRNFPEEINIVPAIKKFTQGKVEFVNGQILEIDSVILATGYTSNVTSWLMESEFFSREGCPKSPFPNGWKGEDGLYAVGFTGIGLFGASIDATNVAQDIAKIWKEQM";

req({
    uri: "http://localhost:3000",
    method: "POST",
    json: { query: seq }
}, function(err, req, body){
    console.log(body);
})